import { GoogleGenerativeAI } from "@google/generative-ai";
import dotenv from "dotenv";

dotenv.config();

const genAI = new GoogleGenerativeAI(process.env.GOOGLE_AI_API_KEY || "");

/**
 * Invokes Gemini 1.5 Flash to convert a user message into a SQL query.
 * @param userMessage The message from the user.
 * @param systemPrompt Instructions for the LLM.
 * @param tableStructure The SQL table structure.
 * @param outputFormat The expected output format.
 * @returns The generated SQL query.
 */
export async function generateSqlFromMessage(
  userMessage: string,
  
): Promise<string> { 
/**
 * Configuration for get_event_data tool.
 * These will be provided later as per user instructions.
 */
const SYSTEM_PROMPT = "You are a SQL expert. Convert the user message into a valid PostgreSQL query.";
const SQL_TABLE_STRUCTURE = `-table_name: agent_output
-table_schema:  public.agent_output (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  agent_name text null,
  agent_response json null,
  status text null,
  user_id text null,
  constraint agent_output_pkey primary key (id)
) TABLESPACE pg_default;
- key column details
  a) agent_name - one of calendar_agent, event_agent, ainews_agent, research_agent, investment_agent, expense_agent 
b) status - success, fail-nodata
`;
const OUTPUT_FORMAT = "Return only the SQL query, no explanation.";

  const prompt = `
${SYSTEM_PROMPT}

User message: ${userMessage}

SQL Table Structure:
${SQL_TABLE_STRUCTURE}

Output Format:
${OUTPUT_FORMAT}
`;

  console.log(`Prompt: ${prompt}`);
  let text = await getLLMResponse(prompt);
  // Clean up SQL if it's wrapped in markdown
  text = text.replace(/```sql/g, "").replace(/```/g, "").trim();
  return text;
}



async function getLLMResponse(
  prompt: string,
): Promise<string> {
  const model = genAI.getGenerativeModel({ model: "gemini-3-flash-preview" });
  
  const result = await model.generateContent(prompt);
  const response = await result.response;
  console.log(`LLM Response: ${response.text()}`);
  return response.text();
}